"""Per-round report (§29). Writes ``rounds/<id>/report.md``.

A conclusion drawn over effects whose deciding term was a gap is refused: the report
prints computability beside every figure rather than a verdict over gaps.
"""
from __future__ import annotations

import json
from collections import Counter

from .calls import absence_record
from .db import DB, ROOT
from .rounds import get_round, meta, state


def round_report(db: DB, round_id: str) -> dict:
    r = get_round(db, round_id)
    L = []
    w = L.append
    w(f"# Round {round_id}: report\n")
    w(f"*Generated by the harness (spec v16 §29). State: `{state(db, round_id)}`. Harness {r['harness_version']}, "
      f"config {str(r['config_hash'])[:12]}, logic {r['logic_version']}.*\n")
    w(f"**Event (Q8 line):** {r['event_line']}  \n**Event date:** {r['event_date']}  \n**Node:** `{r['node']}` "
      f"({r['node_type']}), stratum {r['stratum']}  \n**Class:** {r['round_class']} — {meta(db, round_id, 'class_reasons')}  \n"
      f"**Tags:** {[t['tag'] for t in db.rows('round_tags', 'round_id=?', (round_id,))]}  \n"
      f"**Intake mode:** {r['intake_mode']}, feed `{r['feed_set']}`  \n**Tide:** {meta(db, round_id, 'tide_id')}\n")
    man = db.one("operator_manifests", "round_id=?", (round_id,))
    if man:
        w(f"**Operator:** {man['operator_model']} via {man['operator_runtime']}, cutoff {man['operator_cutoff']} "
          f"({man['cutoff_basis']}), cold={man['cold']}, hook verified={man['hook_verified']}\n")
    calls = db.rows("predictions", "round_id=?", (round_id,))
    res = {}
    for x in db.rows("resolutions", "round_id=?", (round_id,)):
        res[x["call_id"]] = x
    w("## Calls\n")
    w(f"By type: {dict(Counter(c['call_type'] for c in calls))}\n")
    w("| call | type | claim kind | due | outcome | carrier state | branch |\n|---|---|---|---|---|---|---|")
    for c in calls:
        x = res.get(c["call_id"], {})
        w(f"| {c['call_id']} | {c['call_type']} | {c['claim_kind']} | {c['due_at']} | {x.get('outcome', 'open')} | "
          f"{x.get('carrier_state', '')} | {x.get('branch') or ''} |")
    w("")
    w(f"Resolutions by outcome and carrier state: "
      f"{dict(Counter((x['outcome'], x['carrier_state']) for x in res.values()))}  ")
    w(f"Absence record, both rules: {absence_record(db, round_id)}\n")
    w("## Derived ACKs\n")
    ders = db.rows("ack_derivations", "round_id=?", (round_id,))
    w(f"Derivation rows: {dict(Counter(d['result'] for d in ders))}\n")
    for a in [a for a in db.rows("ack_nodes") if a["round_id"] == round_id]:
        w(f"- `{a['key']}` {a['origin']} {a['notice_kind']} status={a['status']} switch={a['is_switch']} "
          f"window_to={a['window_to']} ({a['window_basis']}) fetch_list={len(a.get('fetch_list') or [])}")
    w("")
    w("## Reach and thesis\n")
    for t in db.rows("thesis_sets", "round_id=?", (round_id,)):
        w(f"- {t['ack_id']} seg {t['segment_idx']}: thesis {t['in_thesis']}; exclusions "
          f"{json.dumps(t['exclusions'])[:600]}")
    for o in db.rows("ack_outcomes", "round_id=?", (round_id,)):
        w(f"  - {o['ack_id']} {o['outcome_id']}: {o['reach']} {o['cut_by'] or ''}")
    w("")
    w("## Locks\n")
    for lk in db.rows("locks", "round_id=?", (round_id,)):
        w(f"- segment {lk['segment_idx']} clock {lk['clock']}: lock hash `{lk['lock_hash'][:24]}`")
    w("")
    w("## Vetoes and computability (last lock)\n")
    sr = db.rows("surviving_risk", "round_id=?", (round_id,))
    if sr:
        last = max(x["lock_seq"] for x in sr)
        rows = [x for x in sr if x["lock_seq"] == last]
        w(f"Effects: {len(rows)}; vetoed {sum(x['status'] == 'vetoed' for x in rows)}")
        fired = Counter(v["veto"] for x in rows for v in x["vetoes_fired"])
        w(f"Vetoes fired: {dict(fired)}  ")
        for term in ("stake", "structural", "pricedness", "operator", "expression"):
            have = sum(term in (x["terms"] or {}) for x in rows)
            gaps = Counter((x["gap_reasons"] or {}).get(term) for x in rows if term not in (x["terms"] or {}))
            w(f"- `{term}`: value on {have}/{len(rows)}; gaps {dict(gaps)}")
    w("")
    w("## Stories, junctions, S⊥ (last lock)\n")
    for sc in db.rows("story_classes", "round_id=?", (round_id,)):
        w(f"- seg {sc['segment_idx']} ack {sc['key']}: {sc['story_id']} → {sc['class']} (active={sc['active']}, "
          f"cos={sc['cos']})")
    for j in db.rows("junctions", "round_id=?", (round_id,)):
        w(f"- junction {j['junction_id']}: {j['status']} treatment={j['treatment']}")
    for s in db.rows("s_perp", "round_id=?", (round_id,)):
        w(f"- S⊥ seg {s['segment_idx']} {s['ack_id']} {s['outcome_id']}: |S|={s['s_norm']}, |S⊥|={s['s_perp_norm']}, "
          f"ρ={s['rho']}, flat={s['flat']}")
    w("")
    w("## Baskets\n")
    w("| basket | status | reason | shape | z* | B | max loss |\n|---|---|---|---|---|---|---|")
    for b in db.rows("constructed_baskets", "round_id=?", (round_id,)):
        w(f"| {b['basket_id']} | {b['status']} | {b['reason'] or ''} | {b['shape']} | {b['z_star']} | "
          f"{b['b_basket']} | {b['max_loss']} |")
    w("")
    ex = [e for e in db.rows("paper_exits") if e["basket_id"].startswith(f"B:{round_id}:")]
    if ex:
        w("## Paper book\n")
        for e in ex:
            w(f"- {e['paper_id']} exit {e['at']} ({e['reason']}): pnl {e['pnl']:.2f}, split {e['split']}")
    pianos = db.rows("pianos", "round_id=?", (round_id,))
    w(f"\n## Pianos\n\n{len(pianos)} logged." + "".join(f"\n- {p['description']}" for p in pianos))
    notes = db.rows("notes", "round_id=? AND subject NOT LIKE 'walk_read%'", (round_id,))
    if notes:
        w("\n## Operator notes\n")
        for n in notes:
            w(f"- [{n['subject']}] {n['text']}")
    prov = [m for m in db.rows("round_meta", "round_id=?", (round_id,)) if m["field"].startswith("provisional_keys_read")]
    if prov:
        w(f"\n## Provisional appetite values read\n\n{prov[-1]['value']}")
    text = "\n".join(L) + "\n"
    p = ROOT / "rounds" / round_id / "report.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return {"report": str(p.relative_to(ROOT)), "chars": len(text)}
